### ISSUE TITLE
Admin account

### ISSUE THREAD

**Issue by John-yixiaobao** [UsamaSarwar/reactnative-ecommerce-charlie#7]
Hi, 

I like this e-commerce app, and know how to signup for the common users. but there is an issue about how to setup "admin" account, who has the authority to check the users,orders and listings. please guide me how ? 

thank you

**Comment by UsamaSarwar** [comment]
It's great to hear that you're enjoying the e-commerce app! To set up an "admin" account with the authority to manage users, orders, and listings, you can follow these steps:

1.  **Create Admin Authentication:**
    
    *   You can use Firebase Authentication to create an admin account. Make sure to differentiate admin accounts from regular user accounts by using a unique attribute (e.g., isAdmin) in the user data.
2.  **Database Structure:**
    
    *   In Firebase Realtime Database or Firestore, structure your data to have a separate collection or node for users, orders, and listings.
    *   Use security rules to restrict access to admin-only operations. Only admin users should have write access to certain paths.
3.  **Admin Dashboard:**
    
    *   Develop an admin dashboard within your app. You can create a separate screen that is only accessible by admin users.
    *   Use Firebase Authentication to ensure that only admin users can access the admin dashboard.
4.  **User Management:**
    
    *   In the admin dashboard, implement features to view and manage user accounts. You can display a list of users and allow actions such as blocking, deleting, or updating user profiles.
5.  **Order Management:**
    
    *   Provide functionality to view and manage orders. Admins should be able to see all orders, mark orders as processed, update order statuses, etc.
6.  **Listing Management:**
    
    *   Similarly, implement features to manage listings. Admins should be able to add, edit, and delete listings.
7.  **Security and Authentication:**
    
    *   Implement security rules in Firebase to ensure that only authenticated admin users can perform admin operations.
    *   Regular users should not have access to admin-related functions.

Remember to thoroughly test these functionalities to ensure that admin actions are properly restricted and that regular users cannot access admin features.
