### ISSUE TITLE
Json Parse Error : Unexpected character : <

### ISSUE THREAD

**Issue by duvelltech** [UsamaSarwar/reactnative-ecommerce-charlie#8]
Hello, this project is very interesting. Thanks for sharing. I wasn't able to have it fully functional.

I have the front end running on port 8081 accessible thru expo. The web version is not working.
I have the backend nodejs running on port 3000 with "DB Connection Successfull" in console. If I visit my localhost ip with port :3000, I receive hello world confirming json and api request. I can only access login, sign up and lost password. Is there any default user? How to manage the mongoose database? 

Impossible to create a user or login. Receive : Json Parse Error : Unexpected character : <

Would be nice if you could supply more detail information on how to use this. Thank you, hope to hear from ya

**Comment by UsamaSarwar** [comment]
Hi there, Thanks for checking it out, you may create a new user in MongoDB. Since it is outdated so there might be bugs.
